# Generated by Django 5.2.17 on 2026-09-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr_admin', 'HR Admin'), ('hr', 'HR'), ('interviewer', 'Interviewer'), ('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
