# Generated by Django 5.2.17 on 2026-09-11 01:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=160)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('summary', models.TextField(blank=True)),
                ('resume_url', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('github_url', models.TextField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_ctc', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_ctc', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(max_length=160)),
                ('issued_year', models.PositiveSmallIntegerField()),
                ('credential_url', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-issued_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=40)),
                ('field', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(blank=True, max_length=40, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=160)),
                ('domain', models.CharField(blank=True, max_length=80, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.CharField(db_index=True, max_length=80)),
                ('display_name', models.CharField(max_length=80)),
                ('proficiency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-is_primary', '-proficiency', 'skill'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'skill'), name='candidates_skill_cand_skill_uniq'), models.CheckConstraint(condition=models.Q(('proficiency__gte', 1), ('proficiency__lte', 5)), name='candidates_skill_proficiency_chk')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='candidates.candidate')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['discovered_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'source'), name='candidates_source_cand_src_uniq')],
            },
        ),
    ]
