# Generated by Django 5.2.17 on 2026-09-11 06:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='candidates_candidate_email_ci_unique'),
        ),
    ]
