# Generated by Django 5.2.17 on 2026-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_email_ci_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesource',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('resume', 'Resume Library')], max_length=20),
        ),
    ]
