# Generated by Django 5.2.17 on 2026-09-20 14:29

from django.db import migrations, models


def resume_rows_to_internal(apps, schema_editor):
    """Candidates sourced from an ingested PDF now belong to the internal pool."""
    CandidateSource = apps.get_model("candidates", "CandidateSource")
    for row in CandidateSource.objects.filter(source="resume"):
        if CandidateSource.objects.filter(candidate_id=row.candidate_id, source="internal").exists():
            row.delete()
        else:
            row.source = "internal"
            row.save(update_fields=["source"])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatesource_resume'),
    ]

    operations = [
        migrations.RunPython(resume_rows_to_internal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidatesource',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
