# Generated by Django 5.2.17 on 2026-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_resume_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
