# Generated by Django 5.2.17 on 2026-09-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('status_change', 'Status Change'), ('interview', 'Interview'), ('feedback', 'Feedback'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('mention', 'Mention'), ('system', 'System'), ('support', 'Support')], max_length=20),
        ),
    ]
