import { BriefcaseBusinessIcon, CalendarDaysIcon, FileUserIcon, UsersRoundIcon } from 'lucide-react'

export const CAROUSEL_ITEMS = [
  {
    id: 'resumes',
    label: 'Résumés',
    title: 'Every résumé has a story.',
    description: 'Bring experience, skills, and potential into focus.',
    Icon: FileUserIcon,
    color: '#d8e9a4',
    headline: 'A world of talent.',
    highlight: 'Within your reach.',
    introduction: 'See the experience. Discover the potential.',
    formEyebrow: 'EXPERIENCE. SKILLS. POSSIBILITY.',
    formNote: 'Bring your next great hire into focus.',
    theme: {
      background: '#101b17',
      glow: '#76934e',
      accent: '#d8e9a4',
      muted: '#adbaa3',
      ink: '#263d2c',
      button: '#2b4430',
      buttonHover: '#3b5940',
      card: '#f3f7e9',
      border: '#dce5cf',
    },
  },
  {
    id: 'candidates',
    label: 'Candidates',
    title: 'Meet the people behind the profile.',
    description: 'Discover the strengths that make each person unique.',
    Icon: UsersRoundIcon,
    color: '#abd9c8',
    headline: 'People. Potential.',
    highlight: 'Perfectly connected.',
    introduction: 'Get to know the people who move your team forward.',
    formEyebrow: 'PEOPLE. STRENGTHS. CONNECTIONS.',
    formNote: 'A private space to discover your people.',
    theme: {
      background: '#102020',
      glow: '#428e80',
      accent: '#abd9c8',
      muted: '#a0beb6',
      ink: '#1e3d36',
      button: '#214b42',
      buttonHover: '#306357',
      card: '#edf8f3',
      border: '#cfe5dc',
    },
  },
  {
    id: 'opportunities',
    label: 'Opportunities',
    title: 'Make room for the right connection.',
    description: 'Turn your next open role into someone’s next chapter.',
    Icon: BriefcaseBusinessIcon,
    color: '#edc29d',
    headline: 'The right role.',
    highlight: 'A new beginning.',
    introduction: 'Connect great people with work that matters.',
    formEyebrow: 'NEW ROLES. NEW POSSIBILITIES.',
    formNote: 'Your next great connection starts here.',
    theme: {
      background: '#231b17',
      glow: '#a57951',
      accent: '#edc29d',
      muted: '#c3afa0',
      ink: '#463427',
      button: '#5a4030',
      buttonHover: '#75533c',
      card: '#fcf3e9',
      border: '#eaddce',
    },
  },
  {
    id: 'interviews',
    label: 'Interviews',
    title: 'Great conversations start here.',
    description: 'Bring your team and your next great hire together.',
    Icon: CalendarDaysIcon,
    color: '#c5c4e9',
    headline: 'Let’s connect.',
    highlight: 'Great things await.',
    introduction: 'Bring your next great hire one conversation closer.',
    formEyebrow: 'CONVERSATIONS. CONNECTIONS. GROWTH.',
    formNote: 'Make space for a meaningful conversation.',
    theme: {
      background: '#1a1b2b',
      glow: '#7d7caf',
      accent: '#c5c4e9',
      muted: '#b4b3cd',
      ink: '#33344c',
      button: '#3e4264',
      buttonHover: '#555b83',
      card: '#f2f1fc',
      border: '#deddf0',
    },
  },
] as const

export function wrapCarouselIndex(position: number) {
  return (
    ((Math.round(position) % CAROUSEL_ITEMS.length) + CAROUSEL_ITEMS.length) % CAROUSEL_ITEMS.length
  )
}
