# Generated by Django 5.2.17 on 2026-09-11 01:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('job_description', 'Job Description'), ('candidate_search', 'Candidate Search'), ('candidate_shortlisted', 'Candidate Shortlisted'), ('candidate_contact', 'Candidate Contact'), ('interview', 'Interview'), ('interview_feedback', 'Interview Feedback'), ('candidate_selected', 'Candidate Selected'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('decision', 'Rejected / On Hold')], max_length=32)),
                ('event_type', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='pipeline.application')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='candidates.candidate')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobs.jobdescription')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['job_description', '-occurred_at'], name='activity_jd_occurred_idx'), models.Index(fields=['application', '-occurred_at'], name='activity_app_occurred_idx'), models.Index(fields=['candidate', '-occurred_at'], name='activity_cand_occurred_idx'), models.Index(fields=['category'], name='activity_category_idx')],
            },
        ),
    ]
