# Generated by Django 5.2.17 on 2026-09-11 01:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pipeline.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ai_shortlisted', 'AI Shortlisted'), ('hr_review', 'HR Review'), ('contact_pending', 'Contact Pending'), ('contacted', 'Contacted'), ('phone_screening', 'Phone Screening'), ('interview_scheduled', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('onboarding', 'Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='new', max_length=32)),
                ('previous_status', models.CharField(blank=True, choices=[('new', 'New'), ('ai_shortlisted', 'AI Shortlisted'), ('hr_review', 'HR Review'), ('contact_pending', 'Contact Pending'), ('contacted', 'Contacted'), ('phone_screening', 'Phone Screening'), ('interview_scheduled', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('onboarding', 'Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], max_length=32, null=True)),
                ('entry_source', models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn')], default='internal', max_length=20)),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobdescription')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('domain_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('responsibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('missing_required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('matched_preferred_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('engine', models.CharField(max_length=40)),
                ('engine_version', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='pipeline.application')),
            ],
            options={
                'ordering': ['-overall_pct'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('in_person', 'In Person')], max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('email_sent', 'Email Sent'), ('replied', 'Replied'), ('not_interested', 'Not Interested'), ('callback_requested', 'Callback Requested')], max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=200, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='pipeline.application')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('designation', models.CharField(max_length=120)),
                ('annual_ctc', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('joining_date', models.DateField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='pipeline.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('documents_pending', 'Documents Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='not_started', max_length=20)),
                ('start_date', models.DateField()),
                ('checklist', models.JSONField(blank=True, default=pipeline.models.default_onboarding_checklist)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='pipeline.application')),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_onboardings', to=settings.AUTH_USER_MODEL)),
                ('hr_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_contact_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('new_candidates', models.PositiveIntegerField(default=0)),
                ('existing_candidates', models.PositiveIntegerField(default=0)),
                ('shortlisted', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_runs', to='jobs.jobdescription')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='search_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='pipeline.searchrun'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical'), ('system_design', 'System Design'), ('managerial', 'Managerial'), ('hr', 'HR'), ('final', 'Final')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('mode', models.CharField(choices=[('video', 'Video'), ('phone', 'Phone'), ('onsite', 'On-site')], default='video', max_length=10)),
                ('meeting_link', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('feedback', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_proceed', 'Strong Proceed'), ('proceed', 'Proceed'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20, null=True)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='pipeline.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['scheduled_at'], name='pipeline_interview_sched_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 10)), _connector='OR'), name='pipeline_interview_score_chk')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_description', 'status'], name='pipeline_app_jd_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['last_activity_at'], name='pipeline_app_last_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job_description'), name='pipeline_app_cand_jd_uniq'),
        ),
    ]
