# Generated by Django 5.2.17 on 2026-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatematch',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='rerank_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='retrieval_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='semantic_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='progress',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='query_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='entry_source',
            field=models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('resume', 'Resume Library')], default='internal', max_length=20),
        ),
    ]
