# Generated by Django 5.2.17 on 2026-09-20 14:29

from django.db import migrations, models


def resume_source_to_internal(apps, schema_editor):
    """Applications and search runs that recorded the removed "resume" source."""
    Application = apps.get_model("pipeline", "Application")
    SearchRun = apps.get_model("pipeline", "SearchRun")
    Application.objects.filter(entry_source="resume").update(entry_source="internal")
    for run in SearchRun.objects.filter(sources__contains=["resume"]):
        run.sources = list(dict.fromkeys("internal" if s == "resume" else s for s in run.sources))
        run.save(update_fields=["sources"])


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_semantic_search_fields'),
    ]

    operations = [
        migrations.RunPython(resume_source_to_internal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='entry_source',
            field=models.CharField(choices=[('internal', 'Internal Database'), ('referral', 'Referral'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn')], default='internal', max_length=20),
        ),
    ]
