# Generated by Django 5.2.17 on 2026-09-20 15:54

import uuid
from django.db import migrations, models


DEFAULT_SUBJECT = "{job_title} opportunity at {company}"
DEFAULT_BODY = """Hi {candidate_first_name},

I'm {recruiter_name} from the talent team at {company}. I came across your profile and your experience looks like a strong fit for our {job_title} role.

Would you be open to a short call this week to hear more about the position and share what you're looking for next? If so, reply with a couple of times that suit you and I'll send an invite.

If you'd rather not hear from us about roles, reply "no thanks" and I won't contact you again.

Best regards,
{recruiter_name}
{company} Talent Team"""


def seed_default_template(apps, schema_editor):
    MessageTemplate = apps.get_model("pipeline", "MessageTemplate")
    MessageTemplate.objects.get_or_create(
        name="Introduction: role opportunity",
        defaults={
            "channel": "email",
            "subject": DEFAULT_SUBJECT,
            "body": DEFAULT_BODY,
            "is_default": True,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_remove_resume_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('in_person', 'In Person')], default='email', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    
        migrations.RunPython(seed_default_template, migrations.RunPython.noop),
    ]
