# Generated by Django 5.2.17 on 2026-09-20 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_message_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('knowledge_test', 'Knowledge test'), ('information', 'Share information')], max_length=20)),
                ('mode', models.CharField(default='simulated', max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_answer', 'No answer'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_call_id', models.CharField(blank=True, max_length=120)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('information', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('max_minutes', models.PositiveSmallIntegerField(default=10)),
                ('system_prompt', models.TextField(blank=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('assessment', models.JSONField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_calls', to='pipeline.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
