# Generated by Django 5.2.17 on 2026-09-24 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_phone_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('ai_shortlisted', 'AI Shortlisted'), ('hr_review', 'TA Review'), ('contact_pending', 'Contact Pending'), ('contacted', 'Contacted'), ('phone_screening', 'Phone Screening'), ('interview_scheduled', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'TA Interview'), ('final_interview', 'Final Interview'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('onboarding', 'Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ai_shortlisted', 'AI Shortlisted'), ('hr_review', 'TA Review'), ('contact_pending', 'Contact Pending'), ('contacted', 'Contacted'), ('phone_screening', 'Phone Screening'), ('interview_scheduled', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'TA Interview'), ('final_interview', 'Final Interview'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('onboarding', 'Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.CharField(choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical'), ('system_design', 'System Design'), ('managerial', 'Managerial'), ('hr', 'TA'), ('final', 'Final')], max_length=20),
        ),
        migrations.CreateModel(
            name='SearchChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pipeline.searchrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['search_run', 'user', 'created_at'], name='pipeline_se_search__0edf6b_idx')],
            },
        ),
    ]
