# Generated by Django 5.2.17 on 2026-09-29 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_search_chat_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecall',
            name='questions',
        ),
        migrations.AddField(
            model_name='phonecall',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipeline.interview'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='interview_duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='interview_mode',
            field=models.CharField(choices=[('video', 'Video'), ('phone', 'Phone'), ('onsite', 'On-site')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='interview_round',
            field=models.CharField(blank=True, choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical'), ('system_design', 'System Design'), ('managerial', 'Managerial'), ('hr', 'TA'), ('final', 'Final')], max_length=20),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='purpose',
            field=models.CharField(choices=[('schedule_interview', 'Schedule interview'), ('information', 'Share information')], max_length=20),
        ),
    ]
