# Generated by Django 5.2.17 on 2026-09-11 01:40

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm backs the gin_trgm_ops index on title (plan.md 6.3 JobDescription indexes).
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('experience_min_years', models.PositiveSmallIntegerField()),
                ('experience_max_years', models.PositiveSmallIntegerField()),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=3)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('preferred_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('education_requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('openings', models.PositiveSmallIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_descriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_description_versions', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='jobs.jobdescription')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_recruitment', models.CharField(choices=[('owner', 'Owner'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('interviewer', 'Interviewer'), ('observer', 'Observer')], default='interviewer', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_recruitment_participants', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jobs.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['status'], name='jobs_jd_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['department'], name='jobs_jd_department_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=django.contrib.postgres.indexes.GinIndex(fields=['required_skills'], name='jobs_jd_required_skills_gin'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='jobs_jd_title_trgm_gin'),
        ),
        migrations.AddConstraint(
            model_name='jobdescriptionversion',
            constraint=models.UniqueConstraint(fields=('job_description', 'version'), name='jobs_jdversion_jd_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentparticipant',
            constraint=models.UniqueConstraint(fields=('job_description', 'user'), name='jobs_participant_jd_user_uniq'),
        ),
    ]
