# Generated by Django 5.2.17 on 2026-09-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('force_closed', 'Force Closed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
