# Generated by Django 5.2.17 on 2026-09-25 01:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_jobdescription_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescriptionUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Reading job description"),
                            ("ready", "Ready for review"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["uploading", "processing"])),
                        fields=("uploaded_by",),
                        name="jobs_one_active_upload_per_user",
                    )
                ],
            },
        ),
    ]
