# Generated by Django 5.2.17 on 2026-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdescriptionupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptionupload',
            name='input_file',
            field=models.FileField(blank=True, max_length=500, upload_to='inputs/jobs/%Y/%m/'),
        ),
    ]
