#!/usr/bin/env python3
"""Lock the validated Linux/Python runtime and attach official PyPI artifact hashes.

Run with backend/.venv/bin/python after installing requirements.txt and running
pip check. The resulting lock targets the Linux/Python minor version used here.
It is verified by pip --require-hashes in a clean environment and in Docker.
"""

import concurrent.futures
import importlib.metadata
import json
from pathlib import Path
from urllib.request import urlopen

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

root = Path(__file__).resolve().parent.parent
pending = [
    Requirement(line)
    for raw in (root / "backend/requirements.txt").read_text().splitlines()
    if (line := raw.strip()) and not line.startswith("#")
]
selected = {}
extras_seen = {}
while pending:
    requirement = pending.pop()
    name = canonicalize_name(requirement.name)
    dist = importlib.metadata.distribution(name)
    if not requirement.specifier.contains(dist.version, prereleases=True):
        raise RuntimeError(f"Installed {name} does not satisfy the declared dependency")
    extras = {"", *requirement.extras}
    if name in selected and extras <= extras_seen[name]:
        continue
    selected[name] = dist.version
    extras_seen.setdefault(name, set()).update(extras)
    for value in dist.requires or []:
        child = Requirement(value)
        if child.marker is None or any(
            child.marker.evaluate({"extra": extra}) for extra in extras
        ):
            pending.append(child)


def lock(pair):
    name, version = pair
    with urlopen(
        f"https://pypi.org/pypi/{name}/{version}/json", timeout=60
    ) as response:
        release = json.load(response)
    hashes = sorted(
        {
            file["digests"]["sha256"]
            for file in release["urls"]
            if not file.get("yanked")
        }
    )
    if not hashes:
        raise RuntimeError(f"No published artifacts for {name}")
    return (
        name
        + "=="
        + version
        + " \\\n"
        + " \\\n".join("    --hash=sha256:" + value for value in hashes)
    )


with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
    entries = list(pool.map(lock, sorted(selected.items())))
header = "# Linux / Python 3.12 runtime lock. Generated by scripts/lock_runtime.py.\n# Install with pip --require-hashes -r requirements.lock.\n\n"
(root / "backend/requirements.lock").write_text(header + "\n".join(entries) + "\n")
print(f"Locked {len(entries)} runtime distributions with PyPI SHA-256 hashes")
