# Generated by Django 5.2.17 on 2026-09-16 17:17

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_candidatesource_resume'),
    ]

    operations = [
        # CREATE EXTENSION IF NOT EXISTS vector -- the compose image ships it.
        VectorExtension(),
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('source_path', models.TextField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_size', models.PositiveIntegerField()),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('parse_source', models.CharField(blank=True, max_length=20)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('llm_model', models.CharField(blank=True, max_length=80)),
                ('embedding_model', models.CharField(blank=True, max_length=80)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('storage_status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed')], default='pending_upload', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('storage_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_documents', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('summary', 'Summary'), ('skills', 'Skills'), ('experience', 'Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('projects', 'Projects'), ('text', 'Resume text')], max_length=20)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('char_count', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_chunks', to='candidates.candidate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resumes.resumedocument')),
            ],
            options={
                'ordering': ['document', 'section', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['status'], name='resumes_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['storage_status'], name='resumes_doc_storage_idx'),
        ),
        migrations.AddIndex(
            model_name='resumechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='resumes_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='resumechunk',
            constraint=models.UniqueConstraint(fields=('document', 'section', 'chunk_index'), name='resumes_chunk_doc_section_idx_uniq'),
        ),
    ]
