# Generated by Django 5.2.17 on 2026-09-16 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedocument',
            name='origin',
            field=models.CharField(choices=[('folder', 'Folder scan'), ('upload', 'Uploaded')], default='folder', max_length=10),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='upload_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
