# Generated by Django 5.2.17 on 2026-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_document_origin_upload_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedocument',
            name='input_file',
            field=models.FileField(blank=True, max_length=500, upload_to='inputs/resumes/%Y/%m/'),
        ),
    ]
